POST http://localhost:4000/api/v1/auth/signin HTTP/1.1
Content-Type: application/json

{
    "email": "gaconght@gmail.com",
    "password": "@Abc123123"
}

###
GET http://localhost:4000/api/v1/users/me HTTP/1.1
Content-Type: application/json
Cookie: sid=TyCZZmgfnxFRBHhB4mbyhBKiaIc-l1H8gMRNRFffXMEGahBJqgt5br6fJ4aoN1W82Q5H_TejPgItukj3JUIMU7O8BG-zzJGMxogc91AdTDx96Y9t-XZqfD2TSGA0vTJAEqVr6clZFVmJ; Expires=Mon, 20 Oct 2025 09:12:56 GMT; HttpOnly; Secure; SameSite=lax; Path=/
Accept-Encoding: gzip