POST http://localhost:4000/api/v1/auth/signin HTTP/1.1
Content-Type: application/json
Accept-Encoding: br

{
    "email": "gaconght@gmail.com",
    "password": "@Abc123123"
}

###
GET http://localhost:4000/api/v1/users/me HTTP/1.1
Content-Type: application/json
Cookie: sid=QhZfrUsINGuvkRhU0GI4AV1SLytxsO_ns8IBOB34P5ZuSn0rC-b4l2A371UwFYYoo4zy2JacnghQ1gvcr8dYMhiH4gZEeEeOQt-TIMUei4stQghH9RbQPG7BA-gG7a4whNlOjYmVw6PJ; Expires=Tue, 21 Oct 2025 02:46:01 GMT; HttpOnly; Secure; SameSite=lax; Path=/
Accept-Encoding: br

###
GET http://localhost:4000/api/v1/users HTTP/1.1
Content-Type: application/json
Cookie: sid=QhZfrUsINGuvkRhU0GI4AV1SLytxsO_ns8IBOB34P5ZuSn0rC-b4l2A371UwFYYoo4zy2JacnghQ1gvcr8dYMhiH4gZEeEeOQt-TIMUei4stQghH9RbQPG7BA-gG7a4whNlOjYmVw6PJ; Expires=Tue, 21 Oct 2025 02:46:01 GMT; HttpOnly; Secure; SameSite=lax; Path=/
Accept-Encoding: br

###
GET http://localhost:4000/test1 HTTP/1.1
Content-Type: application/json
Accept-Encoding: gzip
